[project]
name = "probe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "loads>=0.3",
    "numpy>=2.0.2",
    "pandas>=2.3.1",
    "tqdm>=4.67.1",
]
